#!/usr/bin/env zsh

NOCANCEL=false

case $# in
   0|1)
	echo "  zdot_askeitheror - a shellfunction that keeps asking a question until"
	echo "  it is answered properly."
	echo "  The exported variable $ANSWER contains the user-provided answer"
	echo
	echo "  SYNOPSIS:"
	echo
	echo "  zdot_askeitheror [QUESTION] ANSWER1 ANSWER2 [nocancel]"
	echo
	echo "  ANSWER1 is the default answer (the one that is returned when the user just"
	echo "  presses [enter])"
	echo  
	echo "  Possible values for $ANSWER are:"
	echo "    ANSWER1, ANSWER2 (or __cancel__, unless 'nocancel' was set)"
	echo  

   ;;
   2)
	unset QUESTION
	ANSWER1=$1
	ANSWER2=$2
	
   ;;
   3)
	QUESTION="${1} "
	ANSWER1=$2
	ANSWER2=$3
   ;;
   4)
	QUESTION="${1} "
	ANSWER1=$2
	ANSWER2=$3
	NOCANCEL=true
   ;;
   *)
	echo "ERROR: too many arguments ($#) passed to askeitheror()"
	return 2
   ;;
esac

# define the function that actually asks the question
	askloop() {
	    echo -n "${QUESTION}[${ANSWER1}/${ANSWER2}/cancel] "
	    read UANSWER
	    if [ -z "$UANSWER" -o "$UANSWER" = "$ANSWER1" ]; then
			ANSWER=$ANSWER1
			unset UANSWER
			return 0
	    elif [ "$UANSWER" = "$ANSWER2" ]; then
			ANSWER=$ANSWER2
			unset UANSWER
			return 0
	    elif [ "$UANSWER" = "cancel" ]; then
			ANSWER="__cancel__"
			unset UANSWER
			return 0
	    else
			return 1
	    fi
	}
	askloop-nc() {
	    echo -n "${QUESTION}[${ANSWER1}/${ANSWER2}] "
	    read UANSWER
	    if [ -z "$UANSWER" -o "$UANSWER" = "$ANSWER1" ]; then
			ANSWER=$ANSWER1
			unset UANSWER
			return 0
	    elif [ "$UANSWER" = "$ANSWER2" ]; then
			ANSWER=$ANSWER2
			unset UANSWER
			return 0
	    else
			return 1
	    fi
	}

# now the asking:

if [ $NOCANCEL = true ]; then
	RETVAL=1
	while ! [ $RETVAL = 0 ]; do
		askloop-nc
		RETVAL=$?
	done
else 
	while ! [ $RETVAL = 0 ]; do
		askloop
		RETVAL=$?
	done
fi

export ANSWER
