#!/usr/bin/env zsh
#
# zdot_termtitle - function to set the title of a terminal

case $TERM in
  screen)
    # Use these two for GNU Screen:
    print -nR $' 33k'$1$' 33'
    print -nR $' 33]0;'$2$''
    ;;
  (dt|k|E|x)term|rxvt|xterm-*)
    print -Pn '\e]0;'$@
    ;;
esac
