#!/usr/bin/env zsh
#
# zdot_push
#
# a function copies the ssh key and the zsh dotfiles under ~/.zsh to a remote host
#
# Syntax: zdot_push user@host

if [ $# = 0 -o $# -gt 2 ]; then
  cat << EOF

  zdot_push

  A function that copies the (specified) ssh key and the zsh dotfiles under 
  your \$ZDOTDIR to a remote host.

  Syntax: zdot_push [identity_file] user@host

EOF
  return 0
elif [ $# = 1 ]; then
  REMOTE_HOST=$1
elif [ $# = 2 ]; then
  IDENTITY_FILE=$1
  REMOTE_HOST=$2
fi

set -e
zdot_push_sshkey $IDENTITY_FILE $REMOTE_HOST
zdot_push_zdot $REMOTE_HOST
